import {
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsDateString,
  IsEnum,
} from 'class-validator';
import { Transform } from 'class-transformer';
import { TicketStatus } from '@prisma/client';

export class CreateTicketDto {
  // ticketId is auto-generated by the service, so not needed here

  @IsString()
  @IsNotEmpty()
  title: string;

  @IsString()
  @IsNotEmpty()
  description: string;

  @IsString()
  @IsOptional()
  categoryName: string;

  @IsString()
  @IsOptional()
  subCategoryName: string;

  @IsString()
  @IsOptional()
  serviceCategoryName: string;

  @IsNumber()
  @IsOptional()
  @Transform(({ value }) => value ? Number(value) : undefined)
  customerId?: number;

  @IsNumber()
  @IsOptional()
  @Transform(({ value }) => value ? Number(value) : undefined)
  siteId?: number;

  @IsString()
  @IsOptional()
  manCustm?: string;

  @IsString()
  @IsOptional()
  manSite?: string;

  @IsString()
  @IsOptional()
  contactPerson?: string;

  @IsString()
  @IsOptional()
  mobileNo?: string;

  @IsOptional()
  @Transform(({ value }) => value ? new Date(value) : undefined)
  proposedDate?: Date;

  @IsString()
  @IsNotEmpty()
  priority: string;

  @IsEnum(TicketStatus)
  @IsOptional() // optional since default is OPEN
  status?: TicketStatus;

  @IsNumber()
  @IsNotEmpty()
  @Transform(({ value }) => Number(value))
  createdBy: number;

  @IsNumber()
  @IsOptional() // optional since assignedToId is nullable
  @Transform(({ value }) => value ? Number(value) : undefined)
  assignedTo?: number;
}
